sonar.projectKey=test-ci-app
sonar.projectName=Test CI App

sonar.sources=.
sonar.sourceEncoding=UTF-8

# React Native exclusions (VERY important)
sonar.exclusions=node_modules/**,android/**,ios/**

# Focus only JS/TS
sonar.inclusions=**/*.js,**/*.ts,**/*.tsx
